config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'realizacje', to: 'pages#index'
  get 'cennik', to: 'pages#cennik'
  get 'kontakt', to: 'pages#kontakt'
  get 'administrator', to: 'sessions#new'
  post 'administrator', to: 'sessions#create'
  delete 'wyloguj', to: 'sessions#destroy'
  resources :busy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/busy.rb
class Busy < ApplicationRecord
    has_many_attached :images, dependent: :destroy
    validates :name, presence: true, length: {minimum:1, maximum:100}
    validates :opis, presence: true, length: {minimum:1, maximum:1000}
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum: 3, maximum: 25}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/busy_controller.rb
class BusyController < ApplicationController
    before_action :set_busy, only: [:show, :edit, :update, :destroy]
    
    def show

    end

    def index
        @busy = Busy.all
    end

    def new
        @busy = Busy.new
    end

    def create
        @busy = Busy.new(busy_params)
        if @busy.save
            flash[:notice] = "Dodano realizację"
            redirect_to busy_index_path
        else
            render 'new'
        end
    end

    def edit

    end
    def update
    
        if @busy.update(busy_params)
            flash[:notice] = "Poprawnie edytowano realizację."
            redirect_to @busy
        else
            render 'edit'
        end
    end

    def destroy
        @busy.destroy
        redirect_to busy_index_path
    end

    private
    def busy_params
        params.require(:busy).permit(:name,:opis, images:[])
    end

    def set_busy
        @busy = Busy.find(params[:id])
    end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def index

  end

  def cennik

  end

  def kontakt

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Zalogowano pomyślnie"
            redirect_to root_path
        else
            flash.now[:alert] = "Nieprawidłowe hasło lub emial"
            render 'new'
        end

    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Wylogowano użytkownika"
        redirect_to root_path
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
         !!current_user  
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/busy/_form_template.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
        <%= form_with(model: busy, url: url, class: "mb-3", local: true)  do |f| %>
            <div class="form-group row">
                <%= f.label :nazwa, class: "col-1 mr-2 col-form-label font-weight-bold" %>
                <div class="col-12">
                <%= f.text_field :name, class: "form-control", placeholder: "Nazwa realizacji" %>
                </div>
            </div>
            <div class="form-group row">
              <%= f.label :opis, class: "col-1 mr-2 col-form-label font-weight-bold" %>
              <div class="col-12"> 
                <%= f.text_area :opis, rows: 5, class: "form-control", placeholder: "Opis realizacji" %>
              </div>
            </div>
            <% if @akcja == 'new'%>
                <div class="form-group row">
                <%= f.label :zdjęcia, class: "col-1 mr-2 col-form-label font-weight-bold" %>
                <div class="col-12"> 
                    <%= f.file_field :images, multiple: true, class: "form-control", placeholder: "Opis realizacji" %>
                </div>
                </div>
            <% end %>
            <div class="form-group row justify-content-center">
                <% if @akcja == 'new'%>
                    <%= f.submit 'Dodaj', class: "btn btn-outline-success" %>
                <% else %>
                    <%= f.submit 'Edytuj', class: "btn btn-outline-success" %>
                <% end %>
            </div>
        <% end %>

        </div>
    </div>
</div>

app/views/busy/edit.html.erb
<div class="container">
    <div class='row mt-5 mb-5'>
        <div class="col-sm">
            <div class="row">
                <h2>Edycja busów</h2>
            </div>
        </div>
        <div class="col-sm text-right">
            <%= link_to busy_index_path, class:'btn btn-primary button-index'  do %>
            <strong><%= fa_icon 'hand-point-left' %> Powrót</strong>
            <% end %>
        </div>
    </div>    
</div>
<%= render partial: 'form_template', locals: {busy: @busy, url: busy_path(@busy)}%>

app/views/busy/index.html.erb
<div class="container">
    <div class="row mt-5">
        <% if logged_in? %>
            <h3>Tryb administracyjny </h3>
            <%= link_to 'Dodaj realizację', new_busy_path, class:'btn btn-outline-success ml-3' %>
        <% end %>
    </div>
    <div class='row mt-1'>
        <div class="col-sm">
            <div class="row">
                <h2>Realizacje busów</h2>
            </div>
        </div>
        <div class="col-sm text-right">
            <%= link_to realizacje_path, class:'btn btn-primary button-index'  do %>
            <strong><%= fa_icon 'hand-point-left' %> Powrót</strong>
            <% end %>
        </div>
    </div>    
        <% @busy.each do |busy|%>
            <div class="card border-primary mt-5 mb-5">
                <div class="card-body">
                    <div class="row">
                        <% if busy.images[0] != nil %>
                            <% div_id = busy.name -%>
                                
                            <div id="<%= div_id -%>" class="carousel slide mx-auto mt-2" data-ride="carousel" data-wrap="false" data-interval="false" style ="width: 1100px; height: 600px">
                                
                                    <div class="carousel-inner " >
                                        <div class = "carousel-item active" style ="width: 1100px; height: 550px">
                                            <%= image_tag(busy.images[0],class:'d-block w-75 h-100 m-auto') %>
                                        </div>
                                        <% (1...busy.images.count).each do |image|%>
                                            <div class = "carousel-item" style ="width: 1100px; height: 550px">
                                                <%= image_tag(busy.images[image], class:'d-block w-75 h-100 mx-auto') %>
                                            </div>
                                        <% end %>
                                    </div>
                                    <a class="carousel-control-prev" href="#<%= div_id -%>" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#<%= div_id -%>" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                
                            </div>
                        <% end %>
                    </div>
                        <div class="row mb-1">
                            <div class="col-sm">
                                <p class="ml-3"><%= busy.name %></p>
                            </div>
                            <div class="col-sm text-right">
                                <% if logged_in? %>
                                    <%= link_to "Usuń", busy_path(busy), class: "btn btn-outline-danger button-index", method: :delete, data: {confirm: "Na pewno usunąć?"}  %>
                                    <%= link_to 'Edytuj', edit_busy_path(busy), class:'btn btn-outline-info button-index' %>
                                <% end %>
                                <%= link_to 'Pokaż', busy_path(busy), class:'btn btn-outline-primary button-index' %>
                            </div>
                        </div>
                        <button type="button" class="collapsibles">Opis realizacji</button>
                        <div class="content">
                            <p class="card-text mb-3"><%= busy.opis %></p>
                        </div>
                
                </div>
            </div>
        <% end %>
    </div>
        
</div>

<%= javascript_pack_tag 'collapsibles.js' %>

app/views/busy/new.html.erb
<% @akcja = 'new'%>
<div class="container">
    <div class='row mt-5 mb-5'>
        <div class="col-sm">
            <div class="row">
                <h2>Dodanie nowej realizacji</h2>
            </div>
        </div>
        <div class="col-sm text-right">
            <%= link_to busy_index_path, class:'btn btn-primary button-index'  do %>
            <strong><%= fa_icon 'hand-point-left' %> Powrót</strong>
            <% end %>
        </div>
    </div> 
</div>
<%= render partial: 'form_template', locals: {busy: @busy, url: busy_index_path}%>

app/views/busy/show.html.erb
<div class="container">
<div class='row mt-5'>
    <div class="col-sm">
        <div class="row mt-1">
            <h2>Realizacja <%= @busy.name %></h2>
        </div>
    </div>
    <div class="col-sm text-right mt-1">
        <%= link_to busy_index_path, class:'btn btn-primary button-index'  do %>
        <strong><%= fa_icon 'hand-point-left' %> Powrót</strong>
        <% end %>
    </div>
</div>    
    <div class="card border-primary mt-5 mb-5">
        <div class="card-body">
            <div class="row text-center text-lg-left">
                <% (0...@busy.images.count).each do |image|%>
                <div class="col-lg-6 col-md-4 col-6">
                    <div class = "d-block mb-4 h-100">
                        <%= image_tag(@busy.images[image], style: 'display: block; margin: 25px; width: 80%;') %>
                    </div>
                </div>
                <% end %>

            </div>
            <div class="row mb-1">
                <div class="col-sm">
                    <p class="ml-3"><%= @busy.name %></p>
                </div>
                <div class="col-sm text-right">
                    <% if logged_in? %>
                        <%= link_to "Usuń", busy_path(@busy), class: "btn btn-outline-danger button-index", method: :delete, data: {confirm: "Na pewno usunąć?"}  %>
                        <%= link_to 'Edytuj', edit_busy_path(@busy), class:'btn btn-outline-info button-index' %>
                    <% end %>
                </div>
            </div>
            <button type="button" class="collapsibles">Opis realizacji</button>
            <div class="content">
                <p class="card-text mb-3"><%= @busy.opis %></p>
            </div>
        </div>
    </div>
</div>

<%= javascript_pack_tag 'collapsibles.js' %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="bg-dark text-white text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-2">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer Content</h5>
<hr class="my-4">
        <p>
          Tutaj będzie zacny opis firmy Kamila albo coś tam.
        </p>
      </div>
      
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-white">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-white">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messege.html.erb
<% flash.each do |name,msg|%>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_pasek_nawigacji.html.erb
<nav class="navbar navbar-expand navbar-light py-4 navbar-custom">
  <div class="container padding-container">
    <%= link_to root_path do %>
      <% if request.path != root_path %>
        <%= image_tag 'home/logo_male.jpg'%>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if logged_in? %>
          <h2>Tryb admina</h2>
          <%= link_to wyloguj_path, class:"btn btn-outline-danger button-index ml-auto", method: :delete do %>
            <strong class="align-middle">Wyloguj</strong>
          <% end %>
        <% end %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item right-border mr-3 ml-3 <%= 'active' if request.path == cennik_path %>">
          <strong><%= link_to 'Cennik', cennik_path, class: "nav-link" %></strong>
        </li>
        <li class="nav-item right-border mr-4 ml-2 <%= 'active' if request.path == kontakt_path %>">
          <strong><%= link_to 'Kontakt', kontakt_path, class: "nav-link" %></strong>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <strong>Realizacje</strong>
          </a>
          </strong>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Busy', busy_index_path, class:'dropdown-item' %>
            <%= link_to 'Dostawcze', '#', class:'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Nowe Busy', new_busy_path, class:'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrintNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/pasek_nawigacji'%>
    <div id="page-content">
    <%= render 'layouts/messege' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/cennik.html.erb
<div class="container">
    <div class="row mt-3 justify-content-center">
        <h2>Nasz cennik</h2>
    </div>
    <hr class="rounded margin-left-right">
    <div class="row mt-5">
        <div class="col-2">
            <div class="nav flex-column nav-pills mr-5" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Banery</a>
            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Oklejanie</a>
            <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Drukowanie</a>
            </div>
        </div>
        <div class="col-9">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">Usługa</th>
                            <th scope="col">Jednostka</th>
                            <th scope="col">Cena</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                            <td>Baner mały</td>
                            <td>m2</td>
                            <td>10 zł</td>
                            </tr>
                            <tr>
                            <td>Baner duży</td>
                            <td>m2</td>
                            <td>12 zł</td>
                            </tr>
                            <tr>
                            <td>Baner inny</td>
                            <td>m2</td>
                            <td>14 zł</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    <table class="table table-striped">
                            <thead>
                                <tr>
                                <th scope="col">Usługa</th>
                                <th scope="col">Jednostka</th>
                                <th scope="col">Cena</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                <td>Baner</td>
                                <td>Oklejanie</td>
                                <td>Drukowanie</td>
                                </tr>
                                <tr>
                                <td>Jacob</td>
                                <td>Thornton</td>
                                <td>@fat</td>
                                </tr>
                                <tr>
                                <td>Larry</td>
                                <td>the Bird</td>
                                <td>@twitter</td>
                                </tr>
                            </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">Usługa</th>
                            <th scope="col">Jednostka</th>
                            <th scope="col">Cena</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                            <td>Baner</td>
                            <td>Oklejanie</td>
                            <td>Drukowanie</td>
                            </tr>
                            <tr>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                            </tr>
                            <tr>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>@twitter</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron text-center">
        <%= image_tag 'home/logo.jpg' %>
        <h2 class="naglowek">Twoje pomysły nabierają kolorów</h2>
        
        <div class="row margin-bot margin-top">
            <div class="col-sm">
                <h2><%= fa_icon 'cogs' %> Profesjonalizm</h2>
                <hr class="rounded">
                <p>Wieloletnie doświadczenie przekłada się na profesjonalne podejście do każdego zlecenia.</p>
            </div>
            <div class="col-sm">
                <h2><%= fa_icon "thumbs-up" %> Zadowolenie</h2>
                <hr class="rounded">
                <p>Satysafkacja klienta to priorytet dla naszej firmy, dokładamy wszelkich starań, aby spełnić wszelkie oczekiwania.</p>
            </div>
            <div class="col-sm">
                <h2><%= fa_icon "hourglass-end" %> Terminowość</h2>
                <hr class="rounded">
                <p>Czas to pieniądz i my o tym wiemy - usługi wykonywane na czas to podstawa naszej firmy.</p>
            </div>
        </div>
    </div>

    <div class="row margin-bot" >
        <div class="col-sm text-center">
            <div class="inline-photo show-on-scroll">
                <%= image_tag "home/greym4.jpg",class:"img-fluid photo", id:"border" %>
            </div>

        </div>
        <div class="col-sm text-center">
            <div class="header2 show-on-scroll">
                <h1 class="heading">Witamy w New Print!</h1>
                <p class="heading">
                    W naszej firmie od dawna zajmujemy się szeroko rozumianym drukiem. Wykonujemy banery reklamowe, okeljanie samochodów zarówno dużych i małych.
                    Realizujemy nasze projekty od początku do końca. Zapoznaj się z realizacjami.
                </p>
            </div>
            <div class="animacja-button show-on-scroll">
                <%= link_to realizacje_path, class:"btn btn-outline-primary przyciski-home-right" do %>
                    <h2>Realizacje</h2>
                <% end %>
             </div>
        </div>
    </div>

    <div class="row margin-bot" >
        <div class="col-sm text-center">
            <div class="header2 show-on-scroll">
              <h1 class="heading">Kompleksowe projekty!</h1>
              <p class="heading">
                Nasza firma stawia przede wszystkim na profesjonalizm. Już na etapie tworzenia projektu i wyceny mogą Państwo liczyć na nasze profesjonalne podejście.
                Zapraszamy do kontaktu.
              </p>
            </div>
             <div class="animacja-button show-on-scroll">
              <%= link_to realizacje_path, class:"btn btn-outline-primary przyciski-home-left" do %>
                <h2>Wycena
                  <i class="right arrow icon"></i>
                </h2>
              <% end %>
            </div>

        </div>
        <div class="col-sm text-center">
            <div class="inline-photo show-on-scroll">
                <%= image_tag "home/owoce.jpg",class:"img-fluid photo",id: 'border' %>
          </div> 
        </div>
    </div>
</div>

<%= javascript_pack_tag 'animacja_przycisku.js' %>

app/views/pages/index.html.erb
<div class="container">
    <div class="d-flex justify-content-center">
 <h2 class="mt-5">Zapoznaj się z naszymi realizacjami</h2>
 </div>
 <hr class="divider-index">
    <div class="row mt-5 mb-5">
        <div class="col-sm text-center d-flex row justify-content-md-center">
            <div class="card" style="width: 20rem;">
                <%= image_tag 'index_icon/bus-icon.jpg'%>
                <div class="card-body">
                    <p class="card-text">Zrealizowane oklejanie samochodów typu bus.</p>
                    <%= link_to busy_index_path, class:'btn btn-lg mt-3 btn-outline-primary szer-przycisku' do %>
                        <%= fa_icon('bus')%> <strong> Busy</strong>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-sm text-center d-flex row justify-content-md-center">
            <div class="card" style="width: 20rem;">
                <%= image_tag 'index_icon/truck-icon.jpg'%>
                <div class="card-body">
                    <p class="card-text">Zrealizowane oklejanie aut dostawczych.</p>
                    <%= link_to '#', class:'btn btn-lg mt-3 btn-outline-primary szer-przycisku' do %>
                        <%= fa_icon('truck')%> <strong> Dostawcze</strong>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-sm text-center d-flex row justify-content-md-center">
            <div class="card" style="width: 20rem;">
                <%= image_tag 'index_icon/car-icon.jpg'%>
                <div class="card-body">
                    <p class="card-text">Zrealizowane oklejanie aut osobowych.</p>
                    <%= link_to '#', class:'btn btn-lg mt-3 btn-outline-primary szer-przycisku' do %>
                        <%= fa_icon('car')%> <strong> Osobowe</strong>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/kontakt.html.erb
<div class="container">
    <div class="row mt-3 justify-content-center">
        <h2>Skontaktuj się z nami</h2>
    </div>
    <hr class="rounded margin-left-right">
    <div class="row mt-5 justify-content-center">
        <div class="card-deck">
            <div class="card" style="width: 19rem;">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-center"><%= image_tag 'telephone-operator.png'%></h5>
                    <h5 class="card-title text-center">Kamil Celej</h5>
                    <h6 class="card-subtitle mb-3 text-muted text-center">Specjalista od oklejania</h6>
                    <p class="card-text"><%= fa_icon 'phone-square-alt'%> 555-555-555</p>
                    <p class="card-text"><%= fa_icon 'envelope-square'%> oklejacz1@o2.pl</p>
                </div>
            </div>
            <div class="card" style="width: 19rem;">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-center"><%= image_tag 'telephone-operator.png'%></h5>
                    <h5 class="card-title text-center">Kamil Celej</h5>
                    <h6 class="card-subtitle mb-3 text-muted text-center">Specjalista od oklejania</h6>
                    <p class="card-text"><%= fa_icon 'phone-square-alt'%> 555-555-555</p>
                    <p class="card-text"><%= fa_icon 'envelope-square'%> oklejacz1@o2.pl</p>
                </div>
            </div>
            <div class="card" style="width: 19rem;">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-center"><%= image_tag 'telephone-operator.png'%></h5>
                    <h5 class="card-title text-center">Kamil Celej</h5>
                    <h6 class="card-subtitle mb-3 text-muted text-center">Specjalista od oklejania</h6>
                    <p class="card-text"><%= fa_icon 'phone-square-alt'%> 555-555-555</p>
                    <p class="card-text"><%= fa_icon 'envelope-square'%> oklejacz1@o2.pl</p>
                </div>
            </div>
        </div>
    </div>
</div>